# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SunnyDay
email: yangbaojin2015@gmail.com
description: SunnyDay, PHP工程师，从事web相关的开发工作。
keywords: SunnyDay, PHP, Laravel
skill_keywords: [PHP, Javascript, HTML+CSS, Swift, Linux, Laravel, Git, Mac, RESTful, Stackoverflow]

timezone:  PRC
encoding: "utf-8"

baseurl: "" 
url: "http://yangbaojin1988.github.io" 

github_username:  yangbaojin1988
github_url:  https://github.com/yangbaojin1988

gems: [jekyll-paginate]

paginate: 2
paginate_path: "page:num"

# Build settings
markdown: kramdown
highlighter: rouge


# navigation
navs:
  -
    href: /
    label: Home

  -
    href: https://github.com/yangbaojin1988
    label: GitHub
    target: _blank

  -
    href: /about
    label: About